### ISSUE TITLE
Relative date picker

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas-UI#115]
We want to have a component that allows a relative date range from a given point.

- Implemented as a wrapped version of the existing date picker component, to simplify the API
- API for this component should consist of the following parameters:
  - Target Date: Allows the user to either select "interview date", or a specific date. This will be used to calculate the anchor date for the relative range of values
  - Months before: Number of months before the target date. Defaults to 6.
  - Months after: Number of months since the target date. Defaults to 0.
- At runtime, the range parameters of the existing date picker will be set using a combination of the target date, months before, and months after.

**Comment by wwqrd** [comment]
I'm assuming this should round to the start/end of the months.

e.g. if the anchor date was the 14th of Feb, and we specifed a range of 2 months prior, the "min" date would be December 1st.

**Comment by jthrilly** [comment]
Actually no, I think this will be more specific than that. Can you check with @pfsj (perhaps on Slack)>

**Comment by pfsj** [comment]
Yes, the range should probably be required to be a number of days (rather than months) and specifically make the min that exact date.
