### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas-UI#15]
`Icon`s were first noticed to be not displaying in the menu of network-canvas, but they also are not displaying in the ui. The `Icon`s seem to have no color and no size. Possibly related to [this change](https://github.com/codaco/Network-Canvas-UI/pull/12/files#diff-91959a03b1605c786c88f1e993de646a). This is [the last commit that works](https://github.com/codaco/Network-Canvas-UI/commit/74840238f5cbae0caa887ed02d1a942c6f34c455). Giving the `Icon` a "size" or "color" does not seem to make a difference, however giving it a "width" prop does.

**Comment by jamieshark** [comment]
Fixed with https://github.com/codaco/Network-Canvas-UI/pull/16
