### ISSUE TITLE
Remove normalize

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas-UI#29]
Much of the code in our normalization mixin is about fixing rendering differences with browsers that we do not support (IE, Edge, Firefox). This creates parsing overhead, and a needless increase in file size.

Rather than manually removing rules from normalize, or overriding rules in our main stylesheets, I think we should reconsider the purpose and need for normalization more generally. 

It might even be advantageous to let some platform specific CSS in to the app, since it may give us a more native experience (particularly on mobile).

**Comment by jthrilly** [comment]
Thoughts @jamieshark @rebeccamadsen @wwqrd @bryfox?

**Comment by wwqrd** [comment]
I have no preference either way.

Removing it now might break some styles but I'm sure we can fix them.

I know that the `* {}` selector is considered bad for rendering times so it'd be good to get rid of that. I don't know how much overhead the rest adds. This is only affect the initial app render, right?

We'd probably only save a couple of KB file size (not saying that I'm saying we should intentionally waste bytes).

**Comment by rebeccamadsen** [comment]
It's hard to say how much would break unless we tried it. It is probably not a large gain to remove it, but it probably isn't a huge need to have it either.

**Comment by jthrilly** [comment]
I've tested and I don't see any breaking other than we don't specify a default font color (😆) and some of the elements have padding and margin added back to them. 

I'm going to put up a branch with this in, so that you can have a look when you have a moment.

@jamieshark - any thoughts from you? I think the normalize code is something you customized. Is there a way to thin it out (perhaps by platform)?
