### ISSUE TITLE
Multiple includes of global/default, which outputs CSS

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas-UI#41]
A few of the components (button, icons, inputs) are importing all of the global default styles (also imported by all). However, global/default contains CSS rules in addition to SCSS directives, so there are 2-3k duplicated lines of CSS when an app imports `network-canvas-ui/all`.

It would be nice to isolate the re-importable modules for use by those components and keep the CSS-generating files included only by `all`.

**Comment by wwqrd** [comment]
This can probably be resolved by changing to underscored file naming, indicating a partial, and removing the inline `@import`s.

**Comment by wwqrd** [comment]
Also, 2-3k!!!

**Comment by rebeccamadsen** [comment]
Either approach sounds reasonable, but if we don't have a use case for anything other than including 'all' I would probably lean towards the simpler solution. Do we have need to import only pieces of the ui?

**Comment by bryfox** [comment]
Here's what I thought earlier: UI is pretty heavily-geared towards NC; Server won't be using a large part of what it includes. The app could build the render tree faster without the unused CSS.

But (now that you've made me reconsider) that payoff is probably very small even on an older machine, and not worth time spent right now. I'll open a low-hanging-fruit PR; if we ever need partial includes, we can address in the future.
