### ISSUE TITLE
getIcons() and require.context

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas-UI#6]
This line is causing tests to fail in Network-Canvas:

https://github.com/codaco/Network-Canvas-UI/blob/master/src/utils/getIcons.js#L2

Does the config need to change in NC to support it? If so, is there another way we could achieve the same thing to reduce the complexity of integrating with another app? Or do we make webpack a requirement for using UI?

**Comment by jamieshark** [comment]
I believe fixed with 867143d for now
