### ISSUE TITLE
Button cleanup

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas-UI#64]
We need to clarify the situation with the button component, because right now it is a bit of a mess. We want to end up with:

- small, medium, large preset sizes
- ability to color using palette name, with appropriate text/icon color and contrast set automatically.
- an "icon button", which is a round button variant with just a centered icon.

**Comment by wwqrd** [comment]
Button also changes height if the `icon` attribute is set.

**Comment by bryfox** [comment]
We should consider setting `type="button"`, requiring callers to override for other types like "submit" (which is the DOM default, but see https://github.com/codaco/Network-Canvas/pull/740).

**Comment by jthrilly** [comment]
I've added type="button" in a forthcoming PR.
