### ISSUE TITLE
Toggle: Should fieldLabel default to label?

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas-UI#86]
Currently, if a `fieldLabel` isn't provided to `Toggle`, it renders the label (twice):

<img width="489" alt="screen shot 2018-12-04 at 10 54 22 am" src="https://user-images.githubusercontent.com/39674/49454443-2793bb80-f7b3-11e8-84e3-f94c80d0c23f.png">

Is this desired in all cases? In the above example, it feels redundant.

**Comment by jthrilly** [comment]
No, other components don't render the heading label if it isn't explicitly provided. This component should be updated to behave the same way.
